### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by rstropek** [htl-perg-2019-20-5ahif/contact-list-exercise-Alexikon#2]
Hi Alex!

Here is some feedback:

* Do not check in unnecessary folders (e.g. *.vs*, *bin*)
* Use `readonly` if a member does not change after constructor (e.g. `addressBook`)
* Instead of `stringVar == null`, use `string.IsNullOrEmpty`
* No need to call `JsonConvert.SerializeObject` manually (we discussed that today in the lesson)
* Avoid function names starting with lowercase letters (e.g. `findByName`)

In general, requirements are fulfilled. You got your extra point.

Greetings,
Rainer Stropek.

**Comment by Alexikon** [comment]
Thank you for your suggestions.
I changed code to the suggestions of your feedback.

Hopefully, I do not forget them next time.
